package aplicacion.modelo.dominio;
// Generated 07-jun-2018 9:55:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private Integer codigo;
     private Carrera carrera;
     private Perfil perfil;
     private String libretaUniversitaria;
     

    public Alumno() {
    }

    public Alumno(Carrera carrera, Perfil perfil, String libretaUniversitaria) {
        this.carrera = carrera;
        this.perfil = perfil;
        this.libretaUniversitaria = libretaUniversitaria;
    }

     
    /**
     * @return the codigo
     */
    public Integer getCodigo() {
        return codigo;
    }

    /**
     * @param codigo the codigo to set
     */
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    /**
     * @return the carrera
     */
    public Carrera getCarrera() {
        return carrera;
    }

    /**
     * @param carrera the carrera to set
     */
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }

    /**
     * @return the perfil
     */
    public Perfil getPerfil() {
        return perfil;
    }

    /**
     * @param perfil the perfil to set
     */
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }

    /**
     * @return the libretaUniversitaria
     */
    public String getLibretaUniversitaria() {
        return libretaUniversitaria;
    }

    /**
     * @param libretaUniversitaria the libretaUniversitaria to set
     */
    public void setLibretaUniversitaria(String libretaUniversitaria) {
        this.libretaUniversitaria = libretaUniversitaria;
    }


}