package aplicacion.modelo.dominio;
// Generated 07-jun-2018 9:55:55 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Asistencia generated by hbm2java
 */
public class Asistencia  implements java.io.Serializable {


     private Integer codigo;
     private AulaMateria aulaMateria;
     private InscripcionAlumno inscripcionAlumno;
     private Date fecha;
     private String valor;
     private boolean estado;

    public Asistencia() {
    }

    public Asistencia(Integer codigo, AulaMateria aulaMateria, InscripcionAlumno inscripcionAlumno, Date fecha, String valor, boolean estado) {
        this.codigo = codigo;
        this.aulaMateria = aulaMateria;
        this.inscripcionAlumno = inscripcionAlumno;
        this.fecha = fecha;
        this.valor = valor;
        this.estado = estado;
    }
     
     

    /**
     * @return the codigo
     */
    public Integer getCodigo() {
        return codigo;
    }

    /**
     * @param codigo the codigo to set
     */
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    /**
     * @return the aulaMateria
     */
    public AulaMateria getAulaMateria() {
        return aulaMateria;
    }

    /**
     * @param aulaMateria the aulaMateria to set
     */
    public void setAulaMateria(AulaMateria aulaMateria) {
        this.aulaMateria = aulaMateria;
    }

    /**
     * @return the inscripcionAlumno
     */
    public InscripcionAlumno getInscripcionAlumno() {
        return inscripcionAlumno;
    }

    /**
     * @param inscripcionAlumno the inscripcionAlumno to set
     */
    public void setInscripcionAlumno(InscripcionAlumno inscripcionAlumno) {
        this.inscripcionAlumno = inscripcionAlumno;
    }

    /**
     * @return the fecha
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * @param fecha the fecha to set
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * @return the valor
     */
    public String getValor() {
        return valor;
    }

    /**
     * @param valor the valor to set
     */
    public void setValor(String valor) {
        this.valor = valor;
    }

    /**
     * @return the estado
     */
    public boolean isEstado() {
        return estado;
    }

    /**
     * @param estado the estado to set
     */
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

   


}


