package aplicacion.modelo.dominio;
// Generated 07-jun-2018 9:55:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aula generated by hbm2java
 */
public class Aula  implements java.io.Serializable {

    private Integer codigo;
    private String nombre;
    private String descripcion;
    private int capacidad;
    private boolean estado;
    private Set aulasMateriases = new HashSet(0);

    public Aula() {
    }

    public Aula(String nombre, String descripcion, int capacidad, boolean estado) {
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.capacidad = capacidad;
        this.estado = estado;
    }
     
     

    /**
     * @return the codigo
     */
    public Integer getCodigo() {
        return codigo;
    }

    /**
     * @param codigo the codigo to set
     */
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    /**
     * @return the nombre
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * @param nombre the nombre to set
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * @return the descripcion
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * @param descripcion the descripcion to set
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * @return the capacidad
     */
    public int getCapacidad() {
        return capacidad;
    }

    /**
     * @param capacidad the capacidad to set
     */
    public void setCapacidad(int capacidad) {
        this.capacidad = capacidad;
    }

    /**
     * @return the estado
     */
    public boolean isEstado() {
        return estado;
    }

    /**
     * @param estado the estado to set
     */
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    
    @Override
    public boolean equals(Object other) {
        return (other instanceof Aula) && (codigo != null)
            ? codigo.equals(((Aula) other).codigo)
            : (other == this);
    }

    @Override
    public int hashCode() {
        return (codigo != null)
            ? (this.getClass().hashCode() + codigo.hashCode())
            : super.hashCode();
    }

    @Override
    public String toString() {
        return String.format("Aula[%d, %s]", codigo, nombre);
    }

    /**
     * @return the aulasMateriases
     */
    public Set getAulasMateriases() {
        return aulasMateriases;
    }

    /**
     * @param aulasMateriases the aulasMateriases to set
     */
    public void setAulasMateriases(Set aulasMateriases) {
        this.aulasMateriases = aulasMateriases;
    }



}


