package aplicacion.modelo.dominio;
// Generated 07-jun-2018 9:55:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AulaMateria generated by hbm2java
 */
public class AulaMateria  implements java.io.Serializable {


    private Integer codigo;
    private Aula aula;
    private DocenteMateria docenteMateria;
    private String periodo;
    private String comentario;
    private String dia;
    private String horarioDesde;
    private String horarioHasta;
    private boolean estado;
    private String franjaHoraria;
    //private Set asistenciases = new HashSet(0);

    public AulaMateria() {
    }

    public AulaMateria(Aula aula, DocenteMateria docenteMateria, String periodo, String comentario, String dia, String horarioDesde, String horarioHasta, boolean estado, String franjaHoraria) {
        this.aula = aula;
        this.docenteMateria = docenteMateria;
        this.periodo = periodo;
        this.comentario = comentario;
        this.dia = dia;
        this.horarioDesde = horarioDesde;
        this.horarioHasta = horarioHasta;
        this.estado = estado;
        this.franjaHoraria = franjaHoraria;
    }
     
     

    /**
     * @return the codigo
     */
    public Integer getCodigo() {
        return codigo;
    }

    /**
     * @param codigo the codigo to set
     */
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    /**
     * @return the aula
     */
    public Aula getAula() {
        return aula;
    }

    /**
     * @param aula the aula to set
     */
    public void setAula(Aula aula) {
        this.aula = aula;
    }

    /**
     * @return the docenteMateria
     */
    public DocenteMateria getDocenteMateria() {
        return docenteMateria;
    }

    /**
     * @param docenteMateria the docenteMateria to set
     */
    public void setDocenteMateria(DocenteMateria docenteMateria) {
        this.docenteMateria = docenteMateria;
    }

    /**
     * @return the periodo
     */
    public String getPeriodo() {
        return periodo;
    }

    /**
     * @param periodo the periodo to set
     */
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }

    /**
     * @return the comentario
     */
    public String getComentario() {
        return comentario;
    }

    /**
     * @param comentario the comentario to set
     */
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    /**
     * @return the dia
     */
    public String getDia() {
        return dia;
    }

    /**
     * @param dia the dia to set
     */
    public void setDia(String dia) {
        this.dia = dia;
    }

    /**
     * @return the horarioDesde
     */
    public String getHorarioDesde() {
        return horarioDesde;
    }

    /**
     * @param horarioDesde the horarioDesde to set
     */
    public void setHorarioDesde(String horarioDesde) {
        this.horarioDesde = horarioDesde;
    }

    /**
     * @return the horarioHasta
     */
    public String getHorarioHasta() {
        return horarioHasta;
    }

    /**
     * @param horarioHasta the horarioHasta to set
     */
    public void setHorarioHasta(String horarioHasta) {
        this.horarioHasta = horarioHasta;
    }

    /**
     * @return the estado
     */
    public boolean isEstado() {
        return estado;
    }

    /**
     * @param estado the estado to set
     */
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    /**
     * @return the franjaHoraria
     */
    public String getFranjaHoraria() {
        return franjaHoraria;
    }

    /**
     * @param franjaHoraria the franjaHoraria to set
     */
    public void setFranjaHoraria(String franjaHoraria) {
        this.franjaHoraria = franjaHoraria;
    }

    /**
     * @return the asistenciases
     */
    /*public Set getAsistenciases() {
        return asistenciases;
    }*/

    /**
     * @param asistenciases the asistenciases to set
     */
    /*public void setAsistenciases(Set asistenciases) {
        this.asistenciases = asistenciases;
    }*/
}
