package aplicacion.modelo.dominio;
// Generated 07-jun-2018 9:55:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


    private Integer codigo;
    private String nombre;
    private String plan;
    private boolean estado;

    public Carrera() {
    }

    public Carrera(String nombre, String plan, boolean estado) {
        this.nombre = nombre;
        this.plan = plan;
        this.estado = estado;
    }
     
     

    /**
     * @return the codigo
     */
    public Integer getCodigo() {
        return codigo;
    }

    /**
     * @param codigo the codigo to set
     */
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    /**
     * @return the nombre
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * @param nombre the nombre to set
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * @return the plan
     */
    public String getPlan() {
        return plan;
    }

    /**
     * @param plan the plan to set
     */
    public void setPlan(String plan) {
        this.plan = plan;
    }

    /**
     * @return the estado
     */
    public boolean isEstado() {
        return estado;
    }

    /**
     * @param estado the estado to set
     */
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    @Override
    public boolean equals(Object other) {
        return (other instanceof Carrera) && (codigo != null)
            ? codigo.equals(((Carrera) other).codigo)
            : (other == this);
    }

    @Override
    public int hashCode() {
        return (codigo != null)
            ? (this.getClass().hashCode() + codigo.hashCode())
            : super.hashCode();
    }

    @Override
    public String toString() {
        return String.format("Carrera[%d, %s]", codigo, nombre);
    }



}


