package aplicacion.modelo.dominio;
// Generated 07-jun-2018 9:55:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DocenteMateria generated by hbm2java
 */
public class DocenteMateria  implements java.io.Serializable {


    private Integer codigo;
    private Docente docente;
    private Materia materia;
    private int anio;
    private boolean habilitado;
    private boolean estado;

    public DocenteMateria() {
    }

    public DocenteMateria(Docente docente, Materia materia, int anio, boolean habilitado, boolean estado) {
        this.docente = docente;
        this.materia = materia;
        this.anio = anio;
        this.habilitado = habilitado;
        this.estado = estado;
    }
     
     

    /**
     * @return the codigo
     */
    public Integer getCodigo() {
        return codigo;
    }

    /**
     * @param codigo the codigo to set
     */
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    /**
     * @return the docente
     */
    public Docente getDocente() {
        return docente;
    }

    /**
     * @param docente the docente to set
     */
    public void setDocente(Docente docente) {
        this.docente = docente;
    }

    /**
     * @return the materia
     */
    public Materia getMateria() {
        return materia;
    }

    /**
     * @param materia the materia to set
     */
    public void setMateria(Materia materia) {
        this.materia = materia;
    }

    /**
     * @return the anio
     */
    public int getAnio() {
        return anio;
    }

    /**
     * @param anio the anio to set
     */
    public void setAnio(int anio) {
        this.anio = anio;
    }

    /**
     * @return the habilitado
     */
    public boolean isHabilitado() {
        return habilitado;
    }

    /**
     * @param habilitado the habilitado to set
     */
    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }

    /**
     * @return the estado
     */
    public boolean isEstado() {
        return estado;
    }

    /**
     * @param estado the estado to set
     */
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    @Override
    public boolean equals(Object other) {
        return (other instanceof DocenteMateria) && (codigo != null)
            ? codigo.equals(((DocenteMateria) other).codigo)
            : (other == this);
    }

    @Override
    public int hashCode() {
        return (codigo != null)
            ? (this.getClass().hashCode() + codigo.hashCode())
            : super.hashCode();
    }

    @Override
    public String toString() {
        return String.format("DocenteMateria[%d]", codigo);
    }

}


