package aplicacion.modelo.dominio;
// Generated 07-jun-2018 9:55:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * InscripcionAlumno generated by hbm2java
 */
public class InscripcionAlumno  implements java.io.Serializable {


    private Integer codigo;
    private Alumno alumno;
    private DocenteMateria docenteMateria;
    private boolean estado;

    public InscripcionAlumno() {
    }

    public InscripcionAlumno(Alumno alumno, DocenteMateria docenteMateria, boolean estado) {
        this.alumno = alumno;
        this.docenteMateria = docenteMateria;
        this.estado = estado;
    }
     
     

    /**
     * @return the codigo
     */
    public Integer getCodigo() {
        return codigo;
    }

    /**
     * @param codigo the codigo to set
     */
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    /**
     * @return the alumno
     */
    public Alumno getAlumno() {
        return alumno;
    }

    /**
     * @param alumno the alumno to set
     */
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }

    /**
     * @return the docenteMateria
     */
    public DocenteMateria getDocenteMateria() {
        return docenteMateria;
    }

    /**
     * @param docenteMateria the docenteMateria to set
     */
    public void setDocenteMateria(DocenteMateria docenteMateria) {
        this.docenteMateria = docenteMateria;
    }

    /**
     * @return the estado
     */
    public boolean isEstado() {
        return estado;
    }

    /**
     * @param estado the estado to set
     */
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

}


