package aplicacion.modelo.dominio;
// Generated 07-jun-2018 9:55:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Materia generated by hbm2java
 */
public class Materia  implements java.io.Serializable {


    private Integer codigo;
    private Carrera carrera;
    private String nombre;
    private boolean estado;
    //private Set docentesMateriases = new HashSet(0);

    public Materia() {
    }

    public Materia(Integer codigo, Carrera carrera, String nombre, boolean estado) {
        this.codigo = codigo;
        this.carrera = carrera;
        this.nombre = nombre;
        this.estado = estado;
    }
     
     

    /**
     * @return the codigo
     */
    public Integer getCodigo() {
        return codigo;
    }

    /**
     * @param codigo the codigo to set
     */
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    /**
     * @return the carrera
     */
    public Carrera getCarrera() {
        return carrera;
    }

    /**
     * @param carrera the carrera to set
     */
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }

    /**
     * @return the nombre
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * @param nombre the nombre to set
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * @return the estado
     */
    public boolean isEstado() {
        return estado;
    }

    /**
     * @param estado the estado to set
     */
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    
    @Override
    public boolean equals(Object other) {
        return (other instanceof Materia) && (codigo != null)
            ? codigo.equals(((Materia) other).codigo)
            : (other == this);
    }

    @Override
    public int hashCode() {
        return (codigo != null)
            ? (this.getClass().hashCode() + codigo.hashCode())
            : super.hashCode();
    }

    @Override
    public String toString() {
        return String.format("Materia[%d, %s]", codigo, nombre);
    }

    /**
     * @return the docentesMateriases
     */
    /*public Set getDocentesMateriases() {
        return docentesMateriases;
    }*/

    /**
     * @param docentesMateriases the docentesMateriases to set
     */
    /*public void setDocentesMateriases(Set docentesMateriases) {
        this.docentesMateriases = docentesMateriases;
    }*/

}


